name: CraftAttack
previewImage: preview_ca3_spawn_island
description: Spiele mit vielen anderen Spielern auf einem großen Server. Triff dich mit anderen und erschaffe gemeinsam riesige Bauwerke!
order: 500
