name: Kingdoms
previewImage: kg_castle
description: In Kingdoms ging es darum, Königreiche zu gründen, Burgen zu bauen und Krieg gegen andere Königreiche zu führen. Wer wird den Krieg gewinnen?
order: 400
