name: CloudWars
previewImage: preview_cw_top_down
description: CloudWars ist ein Capture the Flag Event. Du musst mit verschiedenen Kits die Flagge des Gegner einsammeln und in deine eigene Burg bringen - aber wer sammelt am Ende mehr Flaggen?
order: 50
